name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
    
# -------------------------- 환경 변수
env:
  PROJECT_NAME: petgoorm_project
  BUCKET_NAME: petgoorm
  CODE_DEPLOY_APP_NAME: pegoorm_cd
  DEPLOYMENT_GROUP_NAME: petgoorm
# -------------------------- 환경 변수

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN_SUBMUDULE }}
          submodules: true
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql root password: ${{ secrets.MARIADB_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
     
      - name: Permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build
        run: ./gradlew build -x test
        
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
